#!/usr/bin/env python3
"""Generate Codex and Copilot/VS Code adapters from the Claude-canonical fleet.

The authored source remains ``agents/*.md`` and ``skills/**``. Other hosts do not share Claude's
agent frontmatter, plugin namespace, hook payload, or skill invocation syntax, so loading those
files unchanged creates plausible-looking but false controls. This generator makes those
differences explicit:

* Copilot/VS Code agents use native tool aliases. Agents protected by Claude's session-wide Bash
  hook receive no ``execute`` tool because neither host exposes the active agent identity on
  ``PreToolUse``.
* Codex agents use standalone TOML and request ``read-only`` or ``workspace-write`` sandbox mode
  from the canonical write-tool authority, while naming that parent permissions can override it.
* Each host gets a skill copy with valid YAML, no Claude plugin namespace, and no direct
  plugin-root paths. Copilot retains its explicit-invocation frontmatter; Codex expresses the
  same rule through ``agents/openai.yaml``.

Every prose projection is declared in ``fleet/hosts/table.py`` with the number of times it must
land across one generation run, and ``expected_outputs`` refuses to hand back bytes whose rewrites
did not land those counts. That closes the class this generator used to carry one anchor at a
time: a canonical sentence is reworded, the rewrite that corrected it silently stops matching, and
the regenerated adapter keeps a Claude-only authority claim that byte-drift validation cannot see,
because the committed copy was produced with the same miss (PR #141 finding).

Generated directories are replaced as a unit by ``--write``, previewed by ``--diff``, and checked
byte-for-byte by the fleet validator. Never edit generated output directly.
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from types import ModuleType

_REPO_ROOT = str(Path(__file__).resolve().parents[1])
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)  # `import fleet` when run as `python3 scripts/<name>.py`

from fleet import frontmatter as _frontmatter  # noqa: E402
from fleet import fs as _fs  # noqa: E402
from fleet import hooks as _hooks  # noqa: E402
from fleet.hosts.rewrites import (  # noqa: E402
    Ledger,
    RewriteError,
    apply_rewrites,
    check_table,
)
from fleet.hosts.table import (  # noqa: E402
    AGENT_REWRITES,
    ALL_REWRITES,
    SECURITY_REFERENCE_REWRITES,
    SKILL_READONLY_REWRITES,
    TEXT_REWRITES,
    TOOLS_REFERENCE_REWRITES,
)
from fleet.hosts.toml import Multiline, TomlEmitError, render_document  # noqa: E402
from fleet.snapshot import (  # noqa: E402
    GATE_ROSTER,
    GATE_SCRIPT,
    GUARD_ROSTER,
    GUARD_SCRIPT,
    HookScript,
)

COPILOT_AGENTS = Path(".github/agents")
CODEX_AGENTS = Path(".codex/agents")
COPILOT_SKILLS = Path(".github/skills")
CODEX_PLUGIN_ROOT = Path("plugins/sde-agents")
CODEX_SKILLS = CODEX_PLUGIN_ROOT / "skills"
GENERATED_ROOTS = (
    COPILOT_AGENTS,
    CODEX_AGENTS,
    COPILOT_SKILLS,
    CODEX_SKILLS,
)
# Retired roots stay declared so `--write` deletes obsolete generated copies instead of leaving a
# second plausible fleet behind. `.claude/agents` was loaded as duplicate agents; the former
# Copilot CLI skill root had no consumer after that lane was retired.
RETIRED_GENERATED_ROOTS = (
    Path("platforms/portable"),
    Path(".claude/agents"),
    Path("platforms/copilot/skills"),
)
HOOKS_FILE = Path("hooks/hooks.json")
# Generated files that are NOT inside a generated root. `--write` replaces a root wholesale, which
# is right for a directory whose every entry it produces; `hooks/` is not that directory -- it is
# the plugin's own hook directory, and deleting it to regenerate one file would take anything a
# future hook adds with it. Declaring the file instead gives it `--write`, `--check`, `--diff`, and
# byte-drift validation without handing the writer a directory it does not own.
GENERATED_FILES = (HOOKS_FILE,)

GENERATED_MARKER = "Generated by scripts/generate_platform_adapters.py; do not edit."
CLAUDE_REFERENCE = Path(
    "prompt-craft/references/claude-code-frontmatter.md"
)
# Which rewrite table each bundled reference is projected through.
RESOURCE_REWRITES = {
    Path("prompt-craft/references/agent-security.md"): SECURITY_REFERENCE_REWRITES,
    Path("prompt-craft/references/tools.md"): TOOLS_REFERENCE_REWRITES,
}

COPILOT_TOOL_ORDER = ("read", "search", "edit", "execute", "web", "agent")
COPILOT_TOOL_MAP = {
    "Read": "read",
    "Grep": "search",
    "Glob": "search",
    "Write": "edit",
    "Edit": "edit",
    "NotebookEdit": "edit",
    "Bash": "execute",
    "WebFetch": "web",
    "WebSearch": "web",
    "Agent": "agent",
}

IDENTITY_FIELDS = (
    "name",
    "version",
    "description",
    "author",
    "homepage",
    "repository",
    "license",
    "keywords",
)
CODEX_COMPONENTS = {
    "skills": "./skills/",
}

_TEXT_RESOURCE_SUFFIXES = {".json", ".md", ".py", ".toml", ".yaml", ".yml"}
_FRONTMATTER_LINE_RE = re.compile(r"^(?P<key>[A-Za-z][A-Za-z0-9_-]*):")


def _validator_module() -> ModuleType:
    """Import the source grammar without making this script depend on its invocation path."""

    try:
        return importlib.import_module("scripts.validate_fleet")
    except ModuleNotFoundError:
        return importlib.import_module("validate_fleet")


def _definition_parts(path: Path) -> tuple[dict[str, str], str, list[str]]:
    """Return parsed fields, body, and raw frontmatter lines for one definition."""

    validator = _validator_module()
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    end = validator.frontmatter_span(lines)
    fields = None if end is None else validator.parse_frontmatter_lines(lines, end)
    if fields is None or end is None:
        raise ValueError(f"{path}: missing or malformed frontmatter")
    missing = sorted({"name", "description"} - fields.keys())
    if missing:
        raise ValueError(
            f"{path}: missing required frontmatter field(s): {', '.join(missing)}"
        )

    body = "\n".join(lines[end + 1 :]).lstrip("\n")
    if text.endswith("\n"):
        body += "\n"
    return fields, body, lines[1:end]


def adapt_text(text: str, host: str, *, ledger: Ledger | None = None) -> str:
    """Apply the shared host projections: runtime references only, prose preserved.

    The rewrites and the count each must land live in `fleet/hosts/table.py`; passing the run's
    ledger is what lets `expected_outputs` fail a generation whose canonical text moved out from
    under a rewrite.
    """

    return apply_rewrites(text, TEXT_REWRITES, host=host, ledger=ledger)


def _copilot_tools(
    fields: dict[str, str], *, guarded: bool
) -> list[str]:
    validator = _validator_module()
    mapped = {
        COPILOT_TOOL_MAP[tool]
        for tool in validator.split_tools(fields.get("tools", ""))
        if tool in COPILOT_TOOL_MAP
    }
    if guarded:
        mapped.discard("execute")
    return [tool for tool in COPILOT_TOOL_ORDER if tool in mapped]


def _has_external_evidence_tools(fields: dict[str, str]) -> bool:
    validator = _validator_module()
    return any(
        tool == "ToolSearch" or tool.startswith("mcp__")
        for tool in validator.split_tools(fields.get("tools", ""))
    )


def _required_skills(fields: dict[str, str]) -> list[str]:
    return [
        entry.strip()
        for entry in fields.get("skills", "").split(",")
        if entry.strip()
    ]


def adapt_agent_contract(
    text: str, *, name: str, host: str, ledger: Ledger | None = None
) -> str:
    """Replace Claude-only authority claims in generated agent prose.

    Callers supply `adapt_text` output, so Agent-tool terminology is already translated;
    `adapt_agent_text` is the composition that guarantees it.
    """

    return apply_rewrites(text, AGENT_REWRITES, host=host, agent=name, ledger=ledger)


def adapt_agent_text(
    text: str, *, name: str, host: str, ledger: Ledger | None = None
) -> str:
    """Project one piece of agent prose: the shared rewrites, then the agent contract.

    The twin of `adapt_skill_text`, and it exists for the same reason. A description and a body
    are both agent prose making the same authority claims, so routing them through different
    rewrite sets let an authority sentence in a description reach both host adapters untouched
    while the ledger's corpus-wide count stayed satisfied by the bodies. One entry point per
    definition kind is the invariant; a count is a total and cannot assert it.
    """

    return adapt_agent_contract(
        adapt_text(text, host, ledger=ledger), name=name, host=host, ledger=ledger
    )


def render_copilot_agent(
    source: Path, *, guarded_names: set[str], ledger: Ledger | None = None
) -> str:
    fields, body, _ = _definition_parts(source)
    name = fields["name"]
    guarded = name in guarded_names
    # The homelab profile depends on a scoped live-effect hook rather than the
    # read-only guard, but this host can scope neither. Its handoff must be a
    # missing capability, not a prose promise beside an execute grant.
    tools = _copilot_tools(fields, guarded=guarded or name == "homelab-engineer")
    description = adapt_agent_text(
        fields["description"], name=name, host="copilot", ledger=ledger
    )
    instructions = adapt_agent_text(
        body.rstrip(), name=name, host="copilot", ledger=ledger
    )

    adapter_lines = [
        "## Host adapter contract",
        "",
        "This generated profile runs on GitHub Copilot and VS Code. Fleet component names are",
        "bare on these hosts; resolve them from the installed plugin using the host's agent or",
        "skill picker.",
    ]
    if guarded:
        adapter_lines.extend(
            [
                "",
                "This profile deliberately receives no shell/execute tool. Claude's source profile",
                "uses a session-wide read-only Bash guard, but Copilot and VS Code PreToolUse",
                "payloads do not identify the active agent. Treat shell inspection as unavailable",
                "and use read/search tools instead.",
            ]
        )
    elif name == "homelab-engineer":
        adapter_lines.extend(
            [
                "",
                "This profile receives no shell/execute tool because this host cannot scope",
                "Claude's live-effect hook to the active agent. Prepare changes with read/search/",
                "edit tools and hand live execution to the operator; do not substitute another",
                "tool to bypass this restriction.",
            ]
        )
    if _has_external_evidence_tools(fields):
        adapter_lines.extend(
            [
                "",
                "Claude-specific MCP tool identifiers are not promised by this adapter. Use an",
                "equivalent connected evidence tool only when the host actually exposes it, keep",
                "its provenance distinct, and label the gap when it is unavailable.",
            ]
        )
    required_skills = _required_skills(fields)
    if required_skills:
        rendered_skills = ", ".join(f"`{skill}`" for skill in required_skills)
        adapter_lines.extend(
            [
                "",
                f"Claude's source profile preloads {rendered_skills}. This host cannot encode that",
                "Claude frontmatter contract; load every listed installed skill before following",
                "the role.",
            ]
        )

    return (
        "---\n"
        f"name: {_frontmatter.yaml_scalar(name)}\n"
        f"description: {_frontmatter.yaml_scalar(description)}\n"
        f"tools: {_frontmatter.yaml_flow_list(tools)}\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER} -->\n\n"
        + "\n".join(adapter_lines)
        + "\n\n"
        + instructions
        + "\n"
    )


def _codex_agent_parts(
    source: Path, *, ledger: Ledger | None = None
) -> tuple[dict[str, str], str, str, str, str]:
    """Return source metadata plus one shared Codex authority contract."""

    validator = _validator_module()
    fields, body, _ = _definition_parts(source)
    name = fields["name"]
    tools = set(validator.split_tools(fields.get("tools", "")))
    sandbox_mode = "workspace-write" if tools & validator.WRITE_TOOLS else "read-only"
    description = adapt_agent_text(
        fields["description"], name=name, host="codex", ledger=ledger
    )
    instructions = adapt_agent_text(
        body.rstrip(), name=name, host="codex", ledger=ledger
    )

    adapter_lines = [
        "Host adapter contract:",
        "- This generated profile is both a source-host project agent and an official Codex",
        "  import source. Fleet component names are bare; in Codex, select skills with the",
        "  skill picker or `$name` syntax.",
        "- Parent session permissions can override this requested sandbox; live permission changes",
        "  and full-access mode are reapplied to child agents.",
        "- The Markdown staging source carries a source-host tool list. Codex custom-agent TOML",
        "  does not provide a per-agent tool allowlist: shell, MCP, skill, and subagent tools may",
        "  remain inherited, so narrower no-shell or no-spawn rules are cooperative unless an",
        "  outer boundary disables those capabilities.",
    ]
    if sandbox_mode == "read-only":
        adapter_lines.extend(
            [
                "- This profile requests `sandbox_mode = \"read-only\"` to match the canonical",
                "  no-write mandate. If the parent grants write authority, that mandate becomes",
                "  cooperative rather than enforced by this profile.",
            ]
        )
    else:
        adapter_lines.extend(
            [
                "- This profile requests `sandbox_mode = \"workspace-write\"` for ordinary local",
                "  workspace changes. Any narrower document-only, test-only, approval, or",
                "  live-effect boundary remains cooperative and must be stated honestly.",
            ]
        )
    if _has_external_evidence_tools(fields):
        adapter_lines.extend(
            [
                "- Source-specific MCP tool IDs are not bundled here. Use equivalent inherited",
                "  evidence tools only when present, preserve provenance, and label unavailable",
                "  evidence instead of inventing it.",
            ]
        )
    required_skills = _required_skills(fields)
    if required_skills:
        rendered_skills = ", ".join(f"`${skill}`" for skill in required_skills)
        adapter_lines.extend(
            [
                f"- The source Markdown profile preloads {rendered_skills}. Invoke every listed",
                "  installed skill before following the role; custom-agent TOML does not package",
                "  the source `skills:` frontmatter.",
            ]
        )

    full_instructions = "\n".join(adapter_lines) + "\n\n" + instructions
    return fields, name, sandbox_mode, description, full_instructions


def render_codex_agent(source: Path, *, ledger: Ledger | None = None) -> str:
    _, name, sandbox_mode, description, full_instructions = _codex_agent_parts(
        source, ledger=ledger
    )
    try:
        return render_document(
            [
                ("name", name),
                ("description", description),
                ("sandbox_mode", sandbox_mode),
                # The trailing newline is part of the value: TOML trims the one that follows the
                # opening delimiter, so this is what keeps the body's final line break.
                ("developer_instructions", Multiline(full_instructions + "\n")),
            ],
            comment=GENERATED_MARKER,
        )
    except TomlEmitError as exc:
        raise ValueError(f"{source}: {exc}") from exc


def _portable_frontmatter(
    lines: list[str],
    fields: dict[str, str],
    *,
    host: str,
    ledger: Ledger | None = None,
) -> tuple[list[str], bool, bool]:
    """Render the canonical scalar subset as YAML accepted by both target hosts."""

    if host not in {"codex", "copilot"}:
        raise ValueError(f"unknown skill adapter host {host!r}")

    output: list[str] = []
    explicit_only = False
    had_tool_deny = False
    for line in lines:
        match = _FRONTMATTER_LINE_RE.match(line)
        if match is None:
            raise ValueError(f"frontmatter line is outside the supported scalar subset: {line!r}")
        key = match.group("key")
        if key == "disallowed-tools":
            had_tool_deny = True
            continue
        if key == "disable-model-invocation":
            explicit_only = fields.get(key, "").lower() == "true"
            if host == "copilot" and explicit_only:
                output.append("disable-model-invocation: true")
            continue

        value = adapt_skill_text(fields.get(key, ""), host, ledger=ledger)
        output.append(f"{key}: {_frontmatter.yaml_scalar(value)}")
    return output, explicit_only, had_tool_deny


def _portable_readonly_body(
    body: str, *, host: str, ledger: Ledger | None = None
) -> str:
    """Remove Claude-only claims from skills whose source has a tool deny."""

    return apply_rewrites(body, SKILL_READONLY_REWRITES, host=host, ledger=ledger)


def adapt_skill_text(text: str, host: str, *, ledger: Ledger | None = None) -> str:
    """Project one piece of skill prose: the shared rewrites, then the read-only claims.

    Every surface a skill's words reach goes through here -- frontmatter values, the body,
    bundled resources, and the Codex policy's description. Routing them separately is what put
    the same false `disallowed-tools` deny into a body, then a bundled resource, then a
    description across three review rounds: each fix closed the surface it was shown while the
    ledger's corpus-wide count stayed satisfied by the surfaces that were already correct, so
    nothing failed. A count cannot catch that -- it is a total, not a coverage proof -- and only
    a single entry point removes the next surface to forget.
    """

    return _portable_readonly_body(
        adapt_text(text, host, ledger=ledger), host=host, ledger=ledger
    )


def adapt_host_resource(
    text: str, *, relative: Path, host: str, ledger: Ledger | None = None
) -> str:
    """Project a bundled prompt-craft reference onto the host it will be read on."""

    table = RESOURCE_REWRITES.get(relative)
    if table is None:
        return text
    return apply_rewrites(text, table, host=host, ledger=ledger)


def render_portable_skill(
    source: Path, *, host: str, ledger: Ledger | None = None
) -> tuple[str, bool]:
    fields, body, frontmatter = _definition_parts(source)
    portable_frontmatter, explicit_only, had_tool_deny = _portable_frontmatter(
        frontmatter,
        fields,
        host=host,
        ledger=ledger,
    )
    # Every skill body, not just one whose frontmatter carries the deny: the claim is false
    # wherever it appears, and gating on the field would let a skill that acquired the sentence
    # without it ship the claim while the ledger's count stayed satisfied. `had_tool_deny` keeps
    # its own job below, which is the adapter note about the dropped field.
    portable_body = adapt_skill_text(body.rstrip(), host, ledger=ledger)

    notes = [
        f"<!-- {GENERATED_MARKER} -->",
        "",
        f"> **{host.title()} adapter:** Fleet component names are bare in this generated copy.",
        "> Resolve them from the installed plugin using the host's agent or skill picker; do "
        "not add",
        "> Claude's plugin namespace.",
    ]
    if explicit_only:
        if host == "copilot":
            notes.append("> This skill is explicit-only through Copilot's frontmatter switch.")
        else:
            notes.append(
                "> This skill is explicit-only through the generated `agents/openai.yaml` policy."
            )
    if had_tool_deny:
        notes.extend(
            [
                "> No single skill-level tool deny is portable across these hosts. The read-only",
                "> mandate is cooperative and the parent host's sandbox or permission profile is",
                "> the enforcement boundary.",
            ]
        )

    return (
        "---\n"
        + "\n".join(portable_frontmatter)
        + "\n---\n\n"
        + "\n".join(notes)
        + "\n\n"
        + portable_body
        + "\n",
        explicit_only,
    )


def render_codex_skill_policy(fields: dict[str, str], *, ledger: Ledger | None = None) -> bytes:
    """Render the Codex-only policy and required interface metadata for one explicit skill."""

    name = fields["name"]
    description = adapt_skill_text(fields["description"], "codex", ledger=ledger)
    short_description = description
    if len(short_description) > 100:
        shortened = short_description[:97].rsplit(" ", 1)[0].rstrip()
        short_description = (shortened or short_description[:97].rstrip()) + "..."
    display_name = name.replace("-", " ").title()
    return (
        "interface:\n"
        f"  display_name: {_frontmatter.yaml_scalar(display_name)}\n"
        f"  short_description: {_frontmatter.yaml_scalar(short_description)}\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    ).encode()


def _hook_roster(root: Path, script: str, constant: str) -> _hooks.Roster:
    """One hook script's subjects and namespace, read as data by the kernel's own reader.

    Never by importing the script: the generator runs against whatever tree it is pointed at, and
    executing that tree's hook to learn who it guards is the thing the guard exists to prevent.
    An unreadable roster raises rather than yielding an empty set, because "guards nobody" and
    "could not be read" render the same adapter and only one of them is true.
    """

    # The hook scripts are canonical sources like `agents/` and `skills/`, and now feed a
    # SHIPPED artifact: a link at `scripts/readonly-guard.py` would make `--write` derive the
    # armed hook from a roster outside the checkout, which byte-drift validation would then
    # certify as current (Copilot, PR #193).
    _assert_canonical_source_path(root / script, root)
    record = HookScript.load(root / script, constant)
    if record.rosters is None:
        raise ValueError(record.error or f"{root / script}: cannot read {constant}")
    return _hooks.Roster(record.rosters[constant], record.rosters.plugin_name)


def _hook_rosters(root: Path) -> tuple[_hooks.Roster, _hooks.Roster]:
    """The guard's and the gate's rosters, read once for the whole generation run.

    One seam, because the two facts are the same fact: the guard roster both renders the armed
    hook and decides which Copilot agents lose `execute`. Reading it twice would let a tree
    regenerate an adapter and a hook that disagree about who is guarded.
    """

    return (
        _hook_roster(root, GUARD_SCRIPT, GUARD_ROSTER),
        _hook_roster(root, GATE_SCRIPT, GATE_ROSTER),
    )


def _is_runtime_byproduct(path: Path) -> bool:
    """Use the shared fleet predicate for execution residue, not a second vocabulary."""

    return _fs.is_runtime_byproduct(path)


def _is_link_or_reparse_point(path: Path) -> bool:
    """Recognize links and Windows reparse points before any read or recursive removal.

    The kernel's check is the one implementation (a former copy here defaulted the reparse flag
    to 0, which silently disabled the junction half on an interpreter lacking the constant). A
    missing entry is not a link; any other stat failure propagates, because an unreadable entry
    is not evidence that it is safe.
    """

    try:
        return _fs.is_link_or_reparse(path)
    except FileNotFoundError:
        return False


def _assert_no_generated_path_indirection(path: Path, *, operation: str) -> None:
    """Fail before a generated-tree operation can cross a filesystem boundary."""

    if _is_link_or_reparse_point(path):
        consequence = (
            "Recursive replacement could delete a different tree."
            if operation == "replace"
            else "Validation could read or certify a different tree."
        )
        raise ValueError(
            f"refusing to {operation} generated path through a link, junction, or reparse "
            f"point: {path}. {consequence}"
        )


def _raise_directory_walk_error(error: OSError) -> None:
    """Make an unreadable generated subtree fail validation instead of disappearing from it."""

    raise error


def _assert_canonical_source_path(path: Path, repository_root: Path) -> None:
    """Reject a canonical resource that escapes through any link-like path component."""

    resolved_root = repository_root.resolve()
    lexical_path = Path(os.path.abspath(path))
    if not lexical_path.is_relative_to(resolved_root):
        raise ValueError(f"canonical source path is outside repository: {lexical_path}")

    current = resolved_root
    for part in lexical_path.relative_to(resolved_root).parts:
        current /= part
        if _is_link_or_reparse_point(current):
            raise ValueError(
                "canonical source path crosses a link, junction, or reparse point: "
                f"{current}. Generation would read or package bytes from a different location."
            )

    resolved_path = lexical_path.resolve(strict=True)
    if not resolved_path.is_relative_to(resolved_root):
        raise ValueError(
            f"canonical source path resolves outside repository: {lexical_path}"
        )


def _canonical_skill_files(root: Path) -> list[Path]:
    """Enumerate canonical skill resources without following directory indirection."""

    resolved_root = root.resolve()
    skills_root = resolved_root / "skills"
    _assert_canonical_source_path(skills_root, resolved_root)
    if not skills_root.is_dir():
        raise ValueError(f"{skills_root}: canonical skill root is not a directory")

    files: list[Path] = []
    for directory_name, directory_names, file_names in os.walk(
        skills_root,
        topdown=True,
        followlinks=False,
    ):
        directory = Path(directory_name)
        _assert_canonical_source_path(directory, resolved_root)
        directory_names.sort()
        for child_name in directory_names:
            child = directory / child_name
            _assert_canonical_source_path(child, resolved_root)
            if not child.is_dir():
                raise ValueError(f"{child}: canonical skill path is not a directory")
        for file_name in sorted(file_names):
            source = directory / file_name
            _assert_canonical_source_path(source, resolved_root)
            if not source.is_file():
                raise ValueError(f"{source}: canonical skill resource is not a regular file")
            files.append(source)
    return files


def _repository_tracked_files(root: Path) -> set[Path] | None:
    """Return tracked paths, or None when Git cannot prove which residue is untracked."""

    try:
        top_level = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
            capture_output=True,
            check=False,
            timeout=10,
        )
        if top_level.returncode:
            return None
        discovered_root = Path(os.fsdecode(top_level.stdout).strip()).resolve()
        if discovered_root != root.resolve():
            return None
        result = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            capture_output=True,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode:
        return None
    return {
        Path(os.fsdecode(raw_path))
        for raw_path in result.stdout.split(b"\0")
        if raw_path
    }


def _canonical_resource_bytes(source: Path) -> bytes:
    """Serialize declared text deterministically while preserving every other resource byte.

    Git normally checks the fleet's text formats out as LF, but a checkout whose attributes were
    applied late can temporarily contain CRLF while its generated copies still contain LF. Raw
    copying then reports host-only drift. Restrict normalization to the repository's explicitly
    textual suffixes: content sniffing could silently corrupt a binary file that happens to decode.
    """

    raw = source.read_bytes()
    if source.suffix.lower() not in _TEXT_RESOURCE_SUFFIXES:
        return raw
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError(
            f"{source}: declared text resource is not valid UTF-8; generation cannot produce "
            "checkout-independent bytes"
        ) from exc
    return text.replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")


def expected_outputs(root: Path, *, verify_rewrites: bool = True) -> dict[Path, bytes]:
    """Return every generated file, keyed by repository-relative path.

    One ledger spans the whole run, and `_assert_rewrites_landed` judges it before any caller
    sees the bytes: a rewrite whose canonical anchor moved would otherwise regenerate a
    clean-looking adapter with the correction silently missing, which byte-drift validation
    cannot catch because the committed copy was produced with the same miss.

    `verify_rewrites=False` is for a SYNTHETIC tree only. The counts in `fleet/hosts/table.py`
    describe this fleet's canonical corpus, so a two-file fixture would report every rewrite as
    missing and say nothing true. Every path that generates the real fleet -- the CLI's
    `--write`, `--check`, and `--diff`, and the validator's adapter rule -- keeps the default.
    """

    root = root.resolve()
    ledger = Ledger()
    outputs: dict[Path, bytes] = {}
    # The hook file is generated from the same rosters the Copilot adapter reads to decide which
    # agents lose `execute`. One read, one fact: a name added to GUARDED_AGENT_NAMES reaches the
    # armed hook and the host adapters in the same regeneration, and cannot reach one without the
    # other (`docs/decisions/2026-09-13-machinery-rewrite.md`, phase 5).
    guard_roster, gate_roster = _hook_rosters(root)
    outputs[HOOKS_FILE] = _hooks.hooks_json(guard_roster, gate_roster)
    guarded_names = set(guard_roster.names)
    agents_root = root / "agents"
    _assert_canonical_source_path(agents_root, root)
    for source in sorted(agents_root.glob("*.md")):
        _assert_canonical_source_path(source, root)
        outputs[COPILOT_AGENTS / f"{source.stem}.agent.md"] = render_copilot_agent(
            source, guarded_names=guarded_names, ledger=ledger
        ).encode("utf-8")
        outputs[CODEX_AGENTS / f"{source.stem}.toml"] = render_codex_agent(
            source, ledger=ledger
        ).encode("utf-8")

    skills_root = root / "skills"
    canonical_skill_files = _canonical_skill_files(root)
    for host, target_root in (
        ("copilot", COPILOT_SKILLS),
        ("codex", CODEX_SKILLS),
    ):
        for source in canonical_skill_files:
            relative = source.relative_to(skills_root)
            if _is_runtime_byproduct(relative):
                continue
            target = target_root / relative
            if source.name == "SKILL.md":
                fields, _, _ = _definition_parts(source)
                rendered, explicit_only = render_portable_skill(
                    source, host=host, ledger=ledger
                )
                outputs[target] = rendered.encode("utf-8")
                if host == "codex" and explicit_only:
                    outputs[target.parent / "agents" / "openai.yaml"] = (
                        render_codex_skill_policy(fields, ledger=ledger)
                    )
            elif source.suffix.lower() == ".md" and relative != CLAUDE_REFERENCE:
                # A bundled resource is skill prose too: the read-only claims are false
                # wherever they appear, and applying them only to SKILL.md left the same hole
                # one level down, with the ledger's count satisfied by the bodies.
                adapted_resource = adapt_host_resource(
                    adapt_skill_text(
                        source.read_text(encoding="utf-8"), host, ledger=ledger
                    ),
                    relative=relative,
                    host=host,
                    ledger=ledger,
                )
                outputs[target] = (
                    f"<!-- {GENERATED_MARKER} -->\n\n"
                    + adapted_resource.rstrip()
                    + "\n"
                ).encode("utf-8")
            else:
                outputs[target] = _canonical_resource_bytes(source)
    if verify_rewrites:
        _assert_rewrites_landed(ledger)
    return outputs


def _assert_rewrites_landed(ledger: Ledger) -> None:
    """Refuse to hand back adapters whose rewrites did not land the counts the table declares."""

    # Before judging the totals, check the table can be judged at all: colliding ids share one
    # ledger entry, so a rewrite that lost its anchor would be covered by its twin's count.
    check_table(ALL_REWRITES)
    shortfalls = ledger.shortfalls(ALL_REWRITES)
    if shortfalls:
        raise RewriteError(
            "host rewrite table is out of step with the canonical fleet:\n- "
            + "\n- ".join(shortfalls)
        )


def _actual_generated_files(
    root: Path,
    *,
    tracked_files: set[Path] | None,
) -> set[Path]:
    root = root.resolve()
    paths: set[Path] = set()
    for relative_root in GENERATED_ROOTS:
        directory = _safe_generated_root(root, relative_root, operation="inspect")
        if not directory.is_dir():
            continue
        for directory_name, directory_names, file_names in os.walk(
            directory,
            topdown=True,
            onerror=_raise_directory_walk_error,
            followlinks=False,
        ):
            current = Path(directory_name)
            _assert_no_generated_path_indirection(current, operation="inspect")
            directory_names.sort()
            for child_name in directory_names:
                _assert_no_generated_path_indirection(
                    current / child_name,
                    operation="inspect",
                )
            for file_name in sorted(file_names):
                path = current / file_name
                _assert_no_generated_path_indirection(path, operation="inspect")
                if not path.is_file():
                    continue
                repository_relative = path.relative_to(root)
                if (
                    _is_runtime_byproduct(path.relative_to(directory))
                    and tracked_files is not None
                    and repository_relative not in tracked_files
                ):
                    continue
                paths.add(repository_relative)
    # Generated files outside the generated roots are named one at a time, so this reports only
    # the ones that exist: a missing one is `expected - actual`, which already has a diagnostic
    # naming the regeneration command. The indirection check is the same one the roots get -- a
    # link here would send `--write` through it to a path outside the repository.
    for relative in GENERATED_FILES:
        path = _safe_generated_file(root, relative, operation="inspect")
        if path.is_file():
            paths.add(relative)
    return paths


def diff_generated_outputs(root: Path) -> list[str]:
    """Render what `--write` would change, as unified diffs against the committed tree.

    A byte-drift failure says only that a file is stale. Reviewing a canonical edit means seeing
    which projected sentence moved, so this renders that directly rather than sending the
    maintainer to regenerate and read `git diff` on a tree they have already overwritten.

    Two kinds of pending change are easy to render as nothing, and both are reported explicitly
    instead: a difference only in line endings or the final newline, which `splitlines()` drops,
    and the retired roots `--write` deletes outright, which are in no expected-output map.
    """

    expected = expected_outputs(root)
    actual = _actual_generated_files(root, tracked_files=_repository_tracked_files(root))
    report: list[str] = []
    for relative in sorted(set(expected) | actual):
        path = root / relative
        wanted = expected.get(relative)
        current = path.read_bytes() if relative in actual and path.is_file() else None
        if wanted == current:
            continue
        name = relative.as_posix()
        try:
            before = "" if current is None else current.decode("utf-8")
            after = "" if wanted is None else wanted.decode("utf-8")
        except UnicodeDecodeError:
            # A binary resource is copied verbatim, so its size is the whole story.
            report.append(
                f"--- {name} (binary: "
                f"{'absent' if current is None else f'{len(current)} bytes'} -> "
                f"{'removed' if wanted is None else f'{len(wanted)} bytes'})"
            )
            continue
        rendered = list(
            difflib.unified_diff(
                before.splitlines(),
                after.splitlines(),
                fromfile=f"{name} (committed)",
                tofile=f"{name} (generated)",
                lineterm="",
            )
        )
        if rendered:
            report.extend(rendered)
            continue
        # The bytes differ but every line's content is equal, so the change is in the line
        # endings or the final newline. Reporting nothing here would let `--diff` exit 0 on a
        # tree `--write` would still rewrite.
        report.append(
            f"--- {name}: same lines, different bytes "
            f"({_line_ending_summary(current)} -> {_line_ending_summary(wanted)})"
        )

    for relative in GENERATED_ROOTS:
        try:
            active = _safe_generated_root(root, relative, operation="inspect")
        except ValueError as exc:
            report.append(f"--- {relative.as_posix()}: cannot inspect generated root safely: {exc}")
            continue
        if active.exists() and not active.is_dir():
            # `--write` unlinks this before recreating the directory. Listing only the child
            # files it will then add would hide the removal entirely.
            report.append(
                f"--- {relative.as_posix()}: generated root is a file, "
                f"would be removed by --write before the directory is recreated"
            )

    for relative in RETIRED_GENERATED_ROOTS:
        try:
            retired = _safe_generated_root(root, relative, operation="inspect")
        except ValueError as exc:
            report.append(f"--- {relative.as_posix()}: cannot inspect retired root safely: {exc}")
            continue
        if not retired.exists():
            continue
        # `--write` deletes these outright; a preview that omitted them would hide the only
        # destructive part of the operation.
        if not retired.is_dir():
            # Not a tree to walk: `rglob` would find nothing and the preview would promise a
            # zero-file removal, which is how it came to disagree with the write.
            report.append(
                f"--- {relative.as_posix()}: retired generated root is a file, "
                f"would be removed by --write"
            )
            continue
        removed = sorted(p for p in retired.rglob("*") if p.is_file())
        report.append(
            f"--- {relative.as_posix()}: retired generated root, {len(removed)} file(s) "
            f"would be removed by --write"
        )
        report.extend(f"-  {p.relative_to(root).as_posix()}" for p in removed)
    return report


def _line_ending_summary(data: bytes | None) -> str:
    """Describe a file's line endings and final newline, for a difference nothing else shows."""

    if data is None:
        return "absent"
    endings = "CRLF" if b"\r\n" in data else ("CR" if b"\r" in data else "LF")
    final = "final newline" if data.endswith(b"\n") else "no final newline"
    return f"{endings}, {final}"


def _output_kind(relative: Path) -> str:
    return "hook file" if relative in GENERATED_FILES else "platform adapter"


def _missing_consequence(relative: Path) -> str:
    """What an ABSENT output costs. Distinct from drift: an absent hook file is not a hook
    covering the wrong roster, it is no hook at all, and an operator triaging the two needs to
    tell an unarmed plugin from a stale one (Copilot, PR #193)."""

    if relative in GENERATED_FILES:
        return (
            "A plugin-shipped agent cannot carry its own hooks, so with this file absent the "
            "read-only guard and the live-effect gate are not attached at all and nothing is "
            "armed;"
        )
    return (
        "Copilot, VS Code, or Codex would silently lose this component;"
    )


def _drift_consequence(relative: Path) -> str:
    """What a STALE output costs -- the hook file is not an adapter.

    A hook whose roster lags its script is not host drift: it is the fleet's only armed control
    disagreeing with the list of agents it is supposed to cover, and it still exits 0.
    """

    if relative in GENERATED_FILES:
        return (
            "The read-only guard and the live-effect gate would cover a roster that is not the "
            "one their scripts declare, and the hook would still exit 0;"
        )
    return (
        "Copilot, VS Code, or Codex would silently get host-dependent behavior with no visible "
        "error;"
    )


def validate_generated_outputs(root: Path) -> list[str]:
    """Report missing, extra, or stale generated files."""

    if not (root / ".claude-plugin" / "plugin.json").is_file():
        return []

    issues: list[str] = []
    try:
        expected = expected_outputs(root)
    except (OSError, ValueError) as exc:
        return [f"{root}: cannot render platform adapters from canonical sources: {exc}"]

    try:
        actual = _actual_generated_files(
            root,
            tracked_files=_repository_tracked_files(root),
        )
    except (OSError, ValueError) as exc:
        return [f"{root}: cannot inspect generated platform adapters: {exc}"]
    for relative in RETIRED_GENERATED_ROOTS:
        retired = root / relative
        try:
            _safe_generated_root(root, relative, operation="inspect")
        except ValueError as exc:
            issues.append(
                f"{retired}: cannot inspect retired generated adapter root safely: {exc} "
                f"To repair, remove the offending link, junction, or reparse point before "
                f"regenerating adapters."
            )
            continue
        if retired.exists():
            issues.append(
                f"{retired}: retired generated adapter root still exists. Both the old shared "
                f"copy and the host-specific copies could be reviewed or packaged as "
                f"authoritative; run `python scripts/generate_platform_adapters.py --write`."
            )
    for relative in sorted(set(expected) - actual):
        issues.append(
            f"{root / relative}: missing generated {_output_kind(relative)}. "
            f"{_missing_consequence(relative)} run "
            f"`python scripts/generate_platform_adapters.py --write`."
        )
    for relative in sorted(actual - set(expected)):
        issues.append(
            f"{root / relative}: stale generated platform adapter has no canonical source. A "
            f"removed component would remain loadable on another host; regenerate the adapters."
        )
    for relative in sorted(set(expected) & actual):
        path = root / relative
        if path.read_bytes() != expected[relative]:
            issues.append(
                f"{path}: generated {_output_kind(relative)} drifted from its canonical source. "
                f"{_drift_consequence(relative)} regenerate it."
            )
    return issues


def _read_manifest(path: Path) -> tuple[dict | None, list[str]]:
    if not path.is_file():
        return None, [f"{path}: missing platform plugin manifest"]
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        return None, [f"{path}: unreadable platform plugin manifest: {exc}"]
    if not isinstance(data, dict):
        return None, [f"{path}: platform plugin manifest must be a JSON object"]
    return data, []


def validate_platform_contracts(root: Path) -> list[str]:
    """Validate manifest parity and host-specific component routing."""

    claude_path = root / ".claude-plugin" / "plugin.json"
    if not claude_path.is_file():
        return []

    codex_path = root / CODEX_PLUGIN_ROOT / ".codex-plugin" / "plugin.json"
    claude, issues = _read_manifest(claude_path)
    codex, read_issues = _read_manifest(codex_path)
    issues.extend(read_issues)
    if claude is None or codex is None:
        return issues

    for field in IDENTITY_FIELDS:
        expected = claude.get(field)
        for label, path, manifest in (("Codex", codex_path, codex),):
            if manifest.get(field) != expected:
                issues.append(
                    f"{path}: {label} manifest field {field!r} differs from the Claude manifest. "
                    f"One release would install under conflicting identity or version metadata."
                )

    for field, expected in CODEX_COMPONENTS.items():
        if codex.get(field) != expected:
            issues.append(
                f"{codex_path}: {field!r} must be {expected!r}. Codex must load the portable "
                f"skill bundle from its isolated plugin root."
            )
    codex_interface = codex.get("interface")
    required_interface_fields = {
        "displayName",
        "shortDescription",
        "longDescription",
        "developerName",
        "category",
    }
    if (
        not isinstance(codex_interface, dict)
        or not required_interface_fields.issubset(codex_interface)
        or not all(
            isinstance(codex_interface[field], str) and codex_interface[field].strip()
            for field in required_interface_fields
            if isinstance(codex_interface, dict)
        )
        or not isinstance(
            codex_interface.get("defaultPrompt") if isinstance(codex_interface, dict) else None,
            list,
        )
        or not isinstance(
            codex_interface.get("capabilities") if isinstance(codex_interface, dict) else None,
            list,
        )
    ):
        issues.append(
            f"{codex_path}: Codex manifest interface is missing required presentation fields. "
            f"Codex plugin ingestion rejects an incomplete marketplace card outside this repo's CI."
        )
    if "agents" in codex:
        issues.append(
            f"{codex_path}: Codex plugin manifests do not package custom agents. Keep standalone "
            f"TOML under .codex/agents and document the separate sync step; an 'agents' manifest "
            f"field would read as distribution while loading nothing."
        )
    if "hooks" in codex:
        issues.append(
            f"{codex_path}: Codex must not load the Claude hook through a manifest override. Keep "
            f"its nested plugin root hook-free and express requested agent sandbox defaults only "
            f"in standalone TOML."
        )

    codex_default_hook = root / CODEX_PLUGIN_ROOT / "hooks" / "hooks.json"
    if codex_default_hook.exists():
        issues.append(
            f"{codex_default_hook}: isolated Codex plugin root must be hook-free. A default hook "
            f"would bypass the host-specific sandbox design."
        )

    marketplace_path = root / ".claude-plugin" / "marketplace.json"
    try:
        marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        issues.append(f"{marketplace_path}: unreadable cross-host marketplace manifest: {exc}")
    else:
        entries = [
            entry
            for entry in marketplace.get("plugins", [])
            if entry.get("name") == claude.get("name")
        ]
        if len(entries) != 1:
            issues.append(
                f"{marketplace_path}: expected exactly one entry for {claude.get('name')!r}; "
                f"Claude marketplace would lose or duplicate the plugin."
            )
        elif entries[0].get("version") != claude.get("version"):
            issues.append(
                f"{marketplace_path}: plugin version differs from the platform manifests. "
                f"Marketplace caches could serve changed files under stale release metadata."
            )

    codex_marketplace_path = root / ".agents" / "plugins" / "marketplace.json"
    try:
        codex_marketplace = json.loads(codex_marketplace_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        issues.append(f"{codex_marketplace_path}: unreadable Codex marketplace manifest: {exc}")
    else:
        codex_entries = [
            entry
            for entry in codex_marketplace.get("plugins", [])
            if entry.get("name") == claude.get("name")
        ]
        expected_source = {
            "source": "local",
            "path": "./plugins/sde-agents",
        }
        if len(codex_entries) != 1:
            issues.append(
                f"{codex_marketplace_path}: expected exactly one Codex marketplace entry for "
                f"{claude.get('name')!r}. Repository installation would not find the nested plugin."
            )
        elif codex_entries[0].get("source") != expected_source:
            issues.append(
                f"{codex_marketplace_path}: Codex marketplace source must be {expected_source!r}. "
                f"The nested plugin isolates Codex from Claude's incompatible default hook."
            )
        if len(codex_entries) == 1:
            entry = codex_entries[0]
            policy = entry.get("policy")
            valid_policy = (
                isinstance(policy, dict)
                and policy.get("installation")
                in {"NOT_AVAILABLE", "AVAILABLE", "INSTALLED_BY_DEFAULT"}
                and policy.get("authentication") in {"ON_INSTALL", "ON_USE"}
            )
            if (
                not valid_policy
                or not isinstance(entry.get("category"), str)
                or not entry["category"].strip()
            ):
                issues.append(
                    f"{codex_marketplace_path}: Codex marketplace entry requires installation "
                    f"policy, authentication timing, and category. An incomplete entry fails only "
                    f"when a consumer tries to install it."
                )

    return issues


def validate_platform_support(root: Path) -> list[str]:
    return validate_platform_contracts(root) + validate_generated_outputs(root)


def _safe_generated_root(root: Path, relative: Path, *, operation: str) -> Path:
    if relative not in (*GENERATED_ROOTS, *RETIRED_GENERATED_ROOTS):
        raise ValueError(f"refusing to {operation} undeclared generated path: {relative}")

    resolved_root = root.resolve()
    target = resolved_root / relative
    if target == resolved_root or not target.is_relative_to(resolved_root):
        raise ValueError(
            f"refusing to {operation} generated path outside repository: {target}"
        )

    current = resolved_root
    for part in relative.parts:
        current /= part
        _assert_no_generated_path_indirection(current, operation=operation)
    return target


def _replace_generated_file(path: Path, content: bytes) -> None:
    """Replace a standalone generated file by directory entry, never by truncating its inode.

    `write_bytes` opens the EXISTING inode and truncates it. A hard link is indistinguishable from
    a regular file -- `lstat` reports one, and the link/reparse checks above cannot see it -- so a
    hard link at `hooks/hooks.json` pointing at a file outside the checkout means `--write`
    silently overwrites that file and leaves the link in place. Reproduced on this PR's own head
    (Codex, PR #193). Writing a sibling temp file and `os.replace`-ing it swaps the directory
    entry instead: the old inode keeps its bytes, the outside file is untouched, and the swap is
    atomic, so a concurrent reader never sees a half-written or absent hook.

    The files inside a generated ROOT do not need this: `--write` removes and recreates those
    directories, so every entry there is a fresh inode before it is written.
    """

    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content)
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _safe_generated_file(root: Path, relative: Path, *, operation: str) -> Path:
    """Resolve a declared standalone generated file, refusing any link-like path COMPONENT.

    `_safe_generated_root`'s sibling, and it walks the ancestors for the same reason: checking
    only the leaf leaves `hooks/` free to be a link, and both validation and `--write` would then
    read and overwrite a file outside the checkout while the repository looked regenerated
    (Copilot, PR #193 -- the leaf-only version shipped in this PR's first push).
    """

    if relative not in GENERATED_FILES:
        raise ValueError(f"refusing to {operation} undeclared generated path: {relative}")

    resolved_root = root.resolve()
    target = resolved_root / relative
    if target == resolved_root or not target.is_relative_to(resolved_root):
        raise ValueError(
            f"refusing to {operation} generated path outside repository: {target}"
        )

    current = resolved_root
    for part in relative.parts:
        current /= part
        _assert_no_generated_path_indirection(current, operation=operation)
    return target


def _remove_generated_root(target: Path) -> None:
    """Clear a generated or retired root, whatever shape it is on disk.

    A declared root that is a regular file is still an obsolete artifact and still has to go;
    `shutil.rmtree` refuses one, which aborted the whole write on a path the preview had already
    promised to remove. The link guard runs before this, so nothing here follows a link.
    """

    if not target.exists():
        return
    if target.is_dir():
        shutil.rmtree(target)
    else:
        target.unlink()


def write_generated_outputs(root: Path) -> int:
    for relative_root in (*RETIRED_GENERATED_ROOTS, *GENERATED_ROOTS):
        _safe_generated_root(root, relative_root, operation="replace")
    expected = expected_outputs(root)
    for relative_root in RETIRED_GENERATED_ROOTS:
        _remove_generated_root(_safe_generated_root(root, relative_root, operation="replace"))
    for relative_root in GENERATED_ROOTS:
        target = _safe_generated_root(root, relative_root, operation="replace")
        _remove_generated_root(target)
        target.mkdir(parents=True)
    for relative, content in expected.items():
        # Re-checked here, not just at inspect time: `--write` is the call that can overwrite a
        # file outside the checkout, and the roots above were cleared and recreated since.
        if relative in GENERATED_FILES:
            # Re-checked here, not just at inspect time: `--write` is the call that can overwrite
            # a file outside the checkout, and the roots above were cleared and recreated since.
            path = _safe_generated_file(root, relative, operation="write")
            path.parent.mkdir(parents=True, exist_ok=True)
            _replace_generated_file(path, content)
            continue
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    return len(expected)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="replace generated adapter directories")
    mode.add_argument("--check", action="store_true", help="check generated output (the default)")
    mode.add_argument(
        "--diff",
        action="store_true",
        help="show what --write would change, without writing",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()

    if args.diff:
        try:
            report = diff_generated_outputs(root)
        except (OSError, ValueError) as exc:
            print(f"Platform adapter diff failed: {exc}", file=sys.stderr)
            return 1
        if not report:
            print("Generated platform adapters match the canonical fleet.")
            return 0
        for line in report:
            print(line)
        return 1

    if args.write:
        try:
            count = write_generated_outputs(root)
        except (OSError, ValueError) as exc:
            print(f"Platform adapter generation failed: {exc}", file=sys.stderr)
            return 1
        adapters = count - len(GENERATED_FILES)
        print(
            f"Generated {adapters} platform adapter files and "
            f"{len(GENERATED_FILES)} hook file(s)."
        )
        return 0

    issues = validate_platform_support(root)
    if issues:
        print("Platform adapter validation failed:", file=sys.stderr)
        for issue in issues:
            print(f"- {issue}", file=sys.stderr)
        return 1
    print("Platform manifests and generated adapters are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
